"use strict";jQuery.fn.tstk_is_bound=function(type){if(this.data('events')!==undefined){if(this.data('events')[type]===undefined||this.data('events')[type].length===0){return false;}
return(-1!==$.inArray(fn,this.data('events')[type]));}else{return false;}};var tstk_anchor_auto_scroll_link=function(){var offset=0;if(jQuery('.tstk-sticky-header.tstk-header-sticky-yes').length>0){offset=offset+jQuery('.tstk-sticky-header.tstk-header-sticky-yes').height();}
if(jQuery('#wpadminbar').length>0&&jQuery(window).width()>600){offset=offset+jQuery('#wpadminbar').height();}
if(window.location.hash){var hash=window.location.hash.substring(1);if(jQuery("#"+hash).length!=0){setTimeout(function(){jQuery('html, body').animate({scrollTop:jQuery('#'+hash).offset().top-offset},500);},100);}}}
var tstk_anchor_link=function(){var nav=jQuery('.mega-menu-wrap, .tstk-navbar > div, .tstk-header-sticky-yes .tstk-navbar > div');var offset=0;if(jQuery('.tstk-sticky-header.tstk-header-sticky-yes').length>0){offset=offset+jQuery('.tstk-sticky-header.tstk-header-sticky-yes').height();}
if(jQuery('#wpadminbar').length>0&&jQuery(window).width()>600){offset=offset+jQuery('#wpadminbar').height();}
nav.find('a').on('click',function(){var $el=jQuery(this),id=$el.attr('href');if(id.includes("#")){var arr=id.split('#')[1];if(jQuery("#"+arr).length!=0){window.history.pushState('page2','Title',id);jQuery(".tstk-navbar > div, body, .mega-menu-wrap").toggleClass("active");jQuery('html, body').animate({scrollTop:jQuery('#'+arr).offset().top-offset},500);return false;}}});}
var tstk_one_page_on_scroll=function(){if(jQuery('body').hasClass('tstk-one-page-site')){var offset=0;if(jQuery('.tstk-sticky-header.tstk-header-sticky-yes').length>0){offset=offset+jQuery('.tstk-sticky-header.tstk-header-sticky-yes').height();}
if(jQuery('#wpadminbar').length>0&&jQuery(window).width()>600){offset=offset+jQuery('#wpadminbar').height();}
var sections=jQuery('.elementor-top-section, section.wpb-content-wrapper > .tstk-row , .tstk-slider-area'),nav=jQuery('.mega-menu-wrap, .tstk-navbar > div'),nav_height=jQuery('.tstk-sticky-header').height();if(jQuery('body').scrollTop()<5){if(jQuery('body').hasClass('home')){nav.find('a').parent().removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');nav.find('a[href="#page"]').parent().addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');}}
var cur_pos=jQuery(window).scrollTop();sections.each(function(){var top=jQuery(this).offset().top-(nav_height+2)-offset,bottom=top+jQuery(this).outerHeight()+offset;if(cur_pos>=top&&cur_pos<=bottom){if(typeof jQuery(this)!='undefined'&&typeof jQuery(this).attr('id')!='undefined'&&jQuery(this).attr('id')!=''){var mainThis=jQuery(this);nav.find('a').removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');jQuery(this).addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');var arr=mainThis.attr('id');nav.find('a').parent().removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');nav.find('a').each(function(){var menuAttr=jQuery(this).attr('href').split('#')[1];if(menuAttr==arr){jQuery(this).parent().addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');}});}}});}}
var tstk_sticky_header=function(){if(jQuery('.tstk-header-sticky-yes').length>0){var header_html=jQuery('#masthead .tstk-main-header-area').html();jQuery('.tstk-sticky-header').append(header_html);jQuery('.tstk-sticky-header .main-navigation ul, .tstk-sticky-header .main-navigation ul li, .tstk-sticky-header .main-navigation ul li a').removeAttr('id');jQuery('.tstk-sticky-header h1').each(function(){var thisele=jQuery(this);var thisele_class=jQuery(this).attr('class');thisele.replaceWith('<span class="'+thisele_class+'">'+jQuery(thisele).html()+'</span>');});if(jQuery('.tstk-main-header-area').hasClass('tstk-infostack-header')){jQuery(".tstk-sticky-header .tstk-header-menu-area").insertAfter(".tstk-sticky-header .site-branding");jQuery('.tstk-sticky-header .tstk-header-info, .tstk-sticky-header .tstk-mobile-search, .tstk-sticky-header .nav-menu-toggle').remove();jQuery(".tstk-sticky-header .tstk-header-left, .tstk-sticky-header .tstk-header-right").remove();}}}
var tstk_sticky_header_class=function(){if(jQuery('#wpadminbar').length>0){jQuery('#masthead').addClass('tstk-adminbar-exists');}
if(jQuery(window).scrollTop()>offset_px){jQuery('#masthead').addClass('tstk-fixed-header');jQuery('.tstk-sticky-header .mega-menu.max-mega-menu.mega-menu-horizontal').attr("id","mega-menu-themestek-top");}else{jQuery('#masthead').removeClass('tstk-fixed-header');}
var offset_px=300;if(jQuery('.tstk-main-header-area').length>0){offset_px=jQuery('.tstk-main-header-area').height()+offset_px;}
jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>offset_px){jQuery('#masthead').addClass('tstk-fixed-header');jQuery('.tstk-sticky-header .mega-menu.max-mega-menu.mega-menu-horizontal').attr("id","mega-menu-themestek-top");}else{jQuery('#masthead').removeClass('tstk-fixed-header');}});}
var tstk_toggleSidebar=function(){jQuery('#menu-toggle').on('click',function(){console.log('Clicked_11');jQuery("body:not(.tstk-max-mega-menu-override) .tstk-navbar > div, body:not(.tstk-max-mega-menu-override)").toggleClass("active");})
if(jQuery('.tstk-navbar > div > .closepanel').length==0){jQuery('.tstk-navbar > div').append('<span class="closepanel"><i class="tstk-base-icon-close-circular-button-symbol"></i></span>');jQuery('.tstk-navbar > div > .closepanel, .tstk-max-mega-menu-override .nav-menu-toggle').on('click',function(){jQuery(".tstk-navbar > div, body, .mega-menu-wrap").toggleClass("active");});if(jQuery('.tstk-main-header-area .tstk-right-box > .tstk-cart-wrapper, .tstk-main-header-area .tstk-right-box .tstk-search-cart-box > .tstk-cart-wrapper').length>0){if(jQuery('.tstk-navbar > div > .tstk-responsive-icons').length==0){jQuery('.tstk-navbar > div').append("<div class='tstk-responsive-icons'></div>");}
jQuery('.tstk-navbar > div > .tstk-responsive-icons').append('<div class="tstk-cart-wrapper"></div>');jQuery('.tstk-navbar > div > .tstk-responsive-icons .tstk-cart-wrapper').append(jQuery('.tstk-main-header-area .tstk-right-box > .tstk-cart-wrapper, .tstk-main-header-area .tstk-right-box .tstk-search-cart-box > .tstk-cart-wrapper').html());}
if(jQuery('.tstk-main-header-area .tstk-right-box > .tstk-header-search-btn, .tstk-main-header-area .tstk-right-box .tstk-search-cart-box > .tstk-header-search-btn').length>0){if(jQuery('.tstk-navbar > div > .tstk-responsive-icons').length==0){jQuery('.tstk-navbar > div').append("<div class='tstk-responsive-icons'></div>");}
jQuery('.tstk-navbar > div > .tstk-responsive-icons').append('<div class="tstk-header-search-btn"></div>');jQuery('.tstk-navbar > div > .tstk-responsive-icons .tstk-header-search-btn').append(jQuery('.tstk-main-header-area .tstk-right-box > .tstk-header-search-btn, .tstk-main-header-area .tstk-right-box .tstk-search-cart-box > .tstk-header-search-btn').html());}
return false;}}
var tstk_wc_cart_page_qty_update=function(){if(typeof jQuery.fn.observe=="function"){jQuery('.wp-block-woocommerce-cart').observe('childlist subtree characterData',function(record){setTimeout(function(){tstk_wc_update_header_cart_total();},500);});jQuery('.wc-block-components-totals-wrapper').observe('childlist subtree characterData',function(record){setTimeout(function(){tstk_wc_update_header_cart_total();},500);});jQuery('.wc-block-components-quantity-selector__button--plus, .wc-block-components-quantity-selector__button--minus, .wc-block-cart-item__remove-link').on('click, mousedown',function(){setTimeout(function(){tstk_wc_update_header_cart_total();},500);});jQuery(".product-quantity .quantity input.input-text.qty, .wc-block-components-quantity-selector__input").on("input",function(){setTimeout(function(){tstk_wc_update_header_cart_total();},500);});}}
var tstk_wc_update_header_cart_total=function(){var total_qty=0;var total_amount='';var curent_qty=0;if(jQuery('table.wc-block-cart-items.wp-block-woocommerce-cart-line-items-block > tbody > tr').length>0){jQuery('table.wc-block-cart-items.wp-block-woocommerce-cart-line-items-block > tbody > tr').each(function(){curent_qty=parseInt(jQuery(this).find('input.wc-block-components-quantity-selector__input').val());total_qty=total_qty+curent_qty;});total_amount=jQuery('.wc-block-components-totals-footer-item-tax-value').html();}
jQuery('.tstk-cart-count').html(total_qty);jQuery('.tstk-cart-wrapper .woocommerce-Price-amount').html(total_amount);}
var tstk_preloader=function(){jQuery(".tstk-preloader").fadeOut('600');}
var tstk_sorting=function(){jQuery('.tstk-sortable-yes:not(.tstk-ajax-sortable-yes)').each(function(){var boxes=jQuery('.tstk-element-posts-wrapper',this);var links=jQuery('.tstk-sortable-list a',this);boxes.isotope({animationEngine:'best-available',layoutMode:'masonry',masonry:{horizontalOrder:true}});links.on('click',function(e){var selector=jQuery(this).data('sortby');if(selector!='*'){var selector='.'+selector;}
boxes.isotope({filter:selector,itemSelector:'.tstk-ele',layoutMode:'fitRows',masonry:{horizontalOrder:true}});links.removeClass('tstk-selected');jQuery(this).addClass('tstk-selected');e.preventDefault();});});}
var tstk_ajax_sorting=function(){jQuery('.themestek-element.tstk-sortable-yes.tstk-ajax-sortable-yes .tstk-sortable-list-ul a').on('click',function(){var thisEle=jQuery(this);var main_ele=jQuery(this).closest('.themestek-element');jQuery('.tstk-element-posts-wrapper',main_ele).addClass('tstk-ajax-loading');var ul_ele=jQuery(this).closest('.tstk-sortable-list-ul');jQuery('a',ul_ele).removeClass('tstk-selected');jQuery(this).addClass('tstk-selected');var cpt=main_ele.data('cpt');var style=main_ele.data('style');var show=main_ele.data('show');var columns=thisEle.data('columns');var from_category=thisEle.data('category');var orderby='';var order='';var selected_category='';var infinitre_scroll_data=jQuery('.tstk-infinite-scroll-data',main_ele).html();if(infinitre_scroll_data!=''){var url_attributes='';jQuery.each(jQuery.parseJSON(infinitre_scroll_data),function(key,value){if(key=='cpt'){cpt=value;}else if(key=='style'){style=value;}else if(key=='show'){show=value;}else if(key=='columns'){columns=value;}else if(key=='orderby'){orderby=value;}else if(key=='order'){order=value;}else if(key=='from_category'){selected_category=value;}});}
if(from_category=='*'&&selected_category!=''){from_category=selected_category.join(',');}
if(from_category=='*'){from_category='';if(selected_category!=''){from_category=selected_category.join(',');}}
jQuery.ajax({type:"post",url:tstk_js_variables.ajaxurl,data:{action:"tstk_ajax_sortable_category",cpt:cpt,style:style,show:show,columns:columns,from_category:from_category,orderby:orderby,order:order,nonce:tstk_js_variables.ajaxnonce_sortcat},success:function(response){jQuery('.tstk-element-posts-wrapper',main_ele).removeClass('tstk-ajax-loading');jQuery('.tstk-element-posts-wrapper',main_ele).html(response);}});return false;});}
var tstk_back_to_top=function(){var btn=jQuery('.scroll-to-top');jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>300){btn.addClass('show');}else{btn.removeClass('show');}});btn.on('click',function(e){e.preventDefault();jQuery('html, body').animate({scrollTop:0},'300');});}
var tstk_navbar=function(){if(!jQuery('ul#tstk-top-menu > li > a[href="#"]').tstk_is_bound('click')){jQuery('ul#tstk-top-menu > li > a[href="#"]').click(function(){return false;});}
jQuery('.tstk-navbar > div > ul li:has(ul)').append("<span class='sub-menu-toggle'><i class='tstk-base-icon-down-open-big'></i></span>");jQuery('.tstk-navbar li').hover(function(){if(jQuery(this).children("ul").length==1){var parent=jQuery(this);var child_menu=jQuery(this).children("ul");if(jQuery(parent).offset().left+jQuery(parent).width()+jQuery(child_menu).width()>jQuery(window).width()){jQuery(child_menu).addClass('tstk-nav-left');}else{jQuery(child_menu).removeClass('tstk-nav-left');}}});jQuery(".nav-menu-toggle").on("click tap",function(){});jQuery('.sub-menu-toggle').on('click',function(){if(jQuery(this).siblings('.sub-menu, .children').hasClass('show')){jQuery(this).siblings('.sub-menu, .children').removeClass('show');jQuery('i',jQuery(this)).removeClass('tstk-base-icon-up-open-big').addClass('tstk-base-icon-down-open-big');}else{jQuery(this).siblings('.sub-menu, .children').addClass('show');jQuery('i',jQuery(this)).removeClass('tstk-base-icon-down-open-big').addClass('tstk-base-icon-up-open-big');}
return false;});jQuery('.nav-menu-toggle').on('click',function(){jQuery('.tstk-navbar ul.menu > li > a').on('click',function(){if(jQuery(this).attr('href')=='#'&&jQuery(this).siblings('ul.sub-menu, ul.children').length>0){jQuery(this).siblings('.sub-menu-toggle').trigger('click');return false;}});})}
var tstk_lightbox=function(){var i_type='image';jQuery('a.tstk-lightbox, a.tstk-lightbox-video, .tstk-lightbox-video a, .tstk-lightbox a').each(function(){if(jQuery(this).hasClass('tstk-lightbox-video')||jQuery(this).closest('.elementor-element').hasClass('tstk-lightbox-video')){i_type='iframe';}else{i_type='image';}
if(jQuery(this).closest('.tstk-ele-portfolio').length==0){jQuery(this).magnificPopup({type:i_type});}});}
var tstk_video_popup=function(){jQuery('.tstk-popup').on('click',function(event){event.preventDefault();var href=jQuery(this).attr('href');var title=jQuery(this).attr('title');window.open(href,title,"width=600,height=500");});}
var tstk_testimonial=function(){jQuery('.tstk-testimonial-active').each(function(){var ele_parent=jQuery(this).closest('.tstk-element-posts-wrapper');jQuery('.themestek-ele.themestek-ele-testimonial',ele_parent).on('mouseover',function(){jQuery('.themestek-ele.themestek-ele-testimonial',ele_parent).removeClass('tstk-testimonial-active');jQuery(this).addClass('tstk-testimonial-active');});});}
var tstk_search_btn=function(){jQuery(function(){jQuery('.tstk-header-search-btn').on("click",function(event){event.preventDefault();jQuery(".tstk-header-search-form-wrapper").addClass("open");jQuery('.tstk-header-search-form-wrapper input[type="search"]').focus();});jQuery(".tstk-search-close").on("click keyup",function(event){jQuery(".tstk-header-search-form-wrapper").removeClass("open");});});}
var tstk_gallery=function(){jQuery("div.tstk-gallery").each(function(){jQuery(this).lightSlider({item:1,auto:true,loop:true,controls:false,speed:1500,pause:5500});});}
var tstk_center_logo_header_class=function(){if(jQuery('#masthead.tstk-header-style-5 ul#tstk-top-menu').length>0){var has_class=jQuery('#masthead.tstk-header-style-5 ul#tstk-top-menu > li').hasClass('tstk-logo-append');if(has_class==false){var total_li=jQuery('#masthead.tstk-header-style-5 ul#tstk-top-menu > li').length;var li=Math.floor(total_li/2);jQuery('#masthead.tstk-header-style-5 ul#tstk-top-menu > li:nth-child('+li+')').addClass('tstk-logo-append');}}}
var tstk_selectwrap=function(){jQuery('select').select2({dropdownParent:jQuery('#page')});}
var tstk_circle_progressbar=function(){jQuery('.tstk-circle-outer').each(function(){var this_circle=jQuery(this);var emptyFill_val="rgba(0, 0, 0, 0)";var thickness_val=10;var fill_val=this_circle.data('fill');var size_val=140;if(typeof this_circle.data('emptyfill')!=='undefined'&&this_circle.data('emptyfill')!=''){emptyFill_val=this_circle.data('emptyfill');}
if(typeof this_circle.data('thickness')!=='undefined'&&this_circle.data('thickness')!=''){thickness_val=this_circle.data('thickness');}
if(typeof this_circle.data('size')!=='undefined'&&this_circle.data('size')!=''){size_val=this_circle.data('size');}
if(typeof this_circle.data('filltype')!=='undefined'&&this_circle.data('filltype')=='gradient'){fill_val={gradient:[this_circle.data('gradient1'),this_circle.data('gradient2')],gradientAngle:Math.PI/4};}
if(typeof jQuery.fn.circleProgress=="function"){var digit=this_circle.data('digit');var before=this_circle.data('before');var after=this_circle.data('after');var digit=Number(digit);var short_digit=(digit/100);jQuery('.tstk-circle',this_circle).circleProgress({value:0,size:size_val,startAngle:-Math.PI/4*2,thickness:thickness_val,emptyFill:emptyFill_val,fill:fill_val}).on('circle-animation-progress',function(event,progress,stepValue){this_circle.find('.tstk-circle-number').html(before+Math.round(stepValue*100)+after);});}
this_circle.waypoint(function(direction){if(!this_circle.hasClass('completed')){if(typeof jQuery.fn.circleProgress=="function"){jQuery('.tstk-circle',this_circle).circleProgress({value:short_digit});};this_circle.addClass('completed');}},{offset:'85%'});});}
var tstk_icon_box_hover_effect=function(){jQuery(".tstk-icon-box-hover-effect .elementor-container .elementor-inner-column").eq(1).addClass('tstk-ihbox-hover-active');jQuery(".tstk-icon-box-hover-effect .elementor-container .elementor-inner-column").mouseover(function(){var main_row=jQuery(this).closest('.tstk-icon-box-hover-effect');jQuery('.elementor-inner-column',main_row).removeClass('tstk-ihbox-hover-active');jQuery(this).addClass('tstk-ihbox-hover-active');});}
var scroll_heading_animation=function(){jQuery(window).width()<1200&&jQuery(".tstk-heading-subheading").each(function(i){var s=jQuery(this).offset().top;}),jQuery(window).scroll(function(){jQuery(".tstk-heading-subheading").each(function(i){var s=jQuery(this).offset().top+jQuery(this).outerHeight()+100;jQuery(window).scrollTop()+jQuery(window).height()>s&&jQuery(this).addClass("tstk-heading-subheading-visible")})})}
var tstk_carousel=function(){jQuery(".themestek-element-viewtype-carousel").each(function(){var carouselElement=jQuery(this);jQuery('.tstk-ele',carouselElement).removeClass(function(index,className){return(className.match(/(^|\s)col-md-\S+/g)||[]).join(' ');}).removeClass(function(index,className){return(className.match(/(^|\s)col-lg-\S+/g)||[]).join(' ');}).removeClass(function(index,className){return(className.match(/(^|\s)wpem-col\S+/g)||[]).join(' ');}).removeClass(function(index,className){return(className.match(/(^|\s)wpem-event-box-col\S+/g)||[]).join(' ');}).removeClass('wpem-col');var columns=jQuery(this).data('columns');var loop=jQuery(this).data('loop');if(columns=='1'){var responsive_items=[1,1,1,1,1];}else if(columns=='2'){var responsive_items=[2,2,2,2,1];}else if(columns=='3'){var responsive_items=[3,2,2,2,1];}else if(columns=='4'){var responsive_items=[4,4,3,2,1];}else if(columns=='5'){var responsive_items=[5,4,3,2,1];}else if(columns=='6'){var responsive_items=[6,4,3,2,1];}else{var responsive_items=[3,3,3,2,1];}
var margin_val=30;if(jQuery(carouselElement).data('margin')!=''){margin_val=jQuery(carouselElement).data('margin');}
var posts_wrapper_class='.tstk-element-posts-wrapper';var val_nav=jQuery(carouselElement).data('nav');if(val_nav=='above'){val_nav=false;}
var val_lasthalf=0;if(jQuery(carouselElement).data('lasthalf')==true){var val_lasthalf=0.5;}
var val_rtl=false;if(jQuery('body').hasClass('rtl')){val_rtl=true;}
var car_options={loop:jQuery(carouselElement).data('loop'),autoplay:jQuery(carouselElement).data('autoplay'),center:jQuery(carouselElement).data('center'),nav:val_nav,rtl:val_rtl,dots:jQuery(carouselElement).data('dots'),autoplaySpeed:jQuery(carouselElement).data('autoplayspeed'),autoplayTimeout:jQuery(carouselElement).data('autoplayspeed')+5000,navSpeed:jQuery(carouselElement).data('autoplayspeed'),dotsSpeed:jQuery(carouselElement).data('autoplayspeed'),dragEndSpeed:jQuery(carouselElement).data('autoplayspeed'),margin:30,items:columns,responsiveClass:true,responsive:{1199:{items:responsive_items[0]+val_lasthalf,},991:{items:responsive_items[1],},767:{items:responsive_items[2],},575:{items:responsive_items[3],},0:{items:responsive_items[4],}}};if(typeof margin_val=="string"&&margin_val!=''){margin_val=margin_val.replace('px','');margin_val=parseInt(margin_val);car_options['margin']=margin_val;}
var tstk_owl=jQuery(posts_wrapper_class,carouselElement).removeClass('row multi-columns-row').addClass('owl-carousel').owlCarousel(car_options).removeClass('wpem-row');jQuery('.tstk-carousel-prev',carouselElement).click(function(event){event.preventDefault();tstk_owl.trigger('prev.owl.carousel',[jQuery(carouselElement).data('autoplayspeed')]);});jQuery('.tstk-carousel-next',carouselElement).click(function(event){event.preventDefault();tstk_owl.trigger('next.owl.carousel',[jQuery(carouselElement).data('autoplayspeed')]);});});};var tstk_menu_count=function(){if(jQuery('ul#tstk-top-menu > li').length>0||jQuery('div#tstk-top-menu > ul > li').length>0){if(jQuery('ul#tstk-top-menu > li').length>0){var total_li=jQuery('ul#tstk-top-menu > li').length;}
if(jQuery('div#tstk-top-menu > ul > li').length>0){var total_li=jQuery('div#tstk-top-menu > ul > li').length;}
if(total_li>6){jQuery('#site-navigation').addClass('tstk-bigger-menu');}}}
var tstk_number_rotate=function(){jQuery(".tstk-number-rotate").each(function(){var self=jQuery(this);var delay=(self.data("appear-animation-delay")?self.data("appear-animation-delay"):0);var animation=self.data("appear-animation");self.html('0');self.waypoint(function(direction){if(!self.hasClass('completed')){var from=self.data('from');var to=self.data('to');var interval=self.data('interval');self.numinate({format:'%counter%',from:from,to:to,runningInterval:2000,stepUnit:interval,onComplete:function(elem){self.addClass('completed');}});}},{offset:'85%'});});};var tstk_img_size_correction=function(){setTimeout(function(){jQuery("img").each(function(){var thisimg=jQuery(this);var p_width=jQuery(this).parent().width();var width=jQuery(this).attr('width');var height=jQuery(this).attr('height');if((typeof width!==typeof undefined&&width!==false)&&(typeof height!==typeof undefined&&height!==false)){var ratio=height/width;jQuery(this).data('tstk-ratio',ratio);var real_width=jQuery(this).width();var new_height=Math.round(real_width*ratio);}});},100);};var tstk_tabs_element=function(){var tabs='';var tab_number='';jQuery('.tstk-tab-link').on('click',function(){if(!jQuery(this).hasClass('tstk-tab-li-active')){var parent=jQuery(this).closest('ul.tstk-tabs-heading');jQuery('li',parent).each(function(){jQuery(this).removeClass('tstk-tab-li-active')});jQuery(this).addClass('tstk-tab-li-active');tab_number=jQuery(this).data('tstk-tab');jQuery(this).parent().parent().find('.tstk-tab-content').removeClass('tstk-tab-active');jQuery(this).parent().parent().find('.tstk-tab-content-'+tab_number).addClass('tstk-tab-active');}});var this_title='';jQuery('.tstk-tab-content-title').on('click',function(){this_title=jQuery(this);tab_number=jQuery(this).data('tstk-tab');jQuery(this).closest('.tstk-tabs').find('li.tstk-tab-link[data-tstk-tab="'+tab_number+'"]',).trigger('click');var animateTo=jQuery(this_title).offset().top-10;if(jQuery('#wpadminbar').length>0){animateTo=animateTo-jQuery('#wpadminbar').height();}
jQuery('html, body').animate({scrollTop:animateTo},500);});};var tstk_infinite_scroll=function(){if(jQuery('.tstk-infinite-scroll-yes').length>0){jQuery('.tstk-infinite-scroll-yes').each(function(){var main_ele=jQuery(this);var style=jQuery(this).data('style');var cpt=jQuery(this).data('cpt');var columns=jQuery(this).data('columns');var show=jQuery(this).data('show');var totalpagination=jQuery(this).data('totalpagination');var infinitre_scroll_data=jQuery('.tstk-infinite-scroll-data',main_ele).html();if(infinitre_scroll_data!=''){var url_attributes='';jQuery.each(jQuery.parseJSON(infinitre_scroll_data),function(key,value){url_attributes=url_attributes+'&'+key+'='+value;});}
if(jQuery(this).hasClass('tstk-infinite-scroll-button-yes')){var x=2;let $grid=jQuery('.tstk-element-posts-wrapper',main_ele).masonry({itemSelector:'none',columnWidth:'.tstk-ele',gutter:0,percentPosition:true,stagger:30,visibleStyle:{transform:'translateY(0)',opacity:1},hiddenStyle:{transform:'translateY(100px)',opacity:0},});let msnry=$grid.data('masonry');$grid.imagesLoaded(function(){$grid.removeClass('are-images-unloaded');$grid.masonry('option',{itemSelector:'.tstk-ele'});let $items=$grid.find('.tstk-ele');$grid.masonry('appended',$items);});$grid.infiniteScroll({path:tstk_js_variables.ajaxurl+'?action=tstk_infinite_scroll&page_no={{#}}&nonce='+tstk_js_variables.ajaxnonce+url_attributes,checkLastPage:false,button:'.tstk-ajax-load-more-btn > a',scrollThreshold:false,status:'.tstk-infinite-loader',append:'.tstk-ele',history:false,visibleStyle:{transform:'translateY(0)',opacity:1},outlayer:msnry,});$grid.on('append.infiniteScroll',function(event,body,path,items,response){jQuery(items).each(function(){jQuery(this).addClass('tstk-infinite-scroll-animation');});if(x>=totalpagination){jQuery('.tstk-ajax-load-more-btn > a',main_ele).hide();jQuery('.tstk-infinite-loader',main_ele).addClass('tstk-infinite-loader-hide');jQuery('.tstk-infinite-scroll-last',main_ele).show();}
x++;});}else{var x=2;if(x>=totalpagination){jQuery('.tstk-ajax-load-more-btn > a',main_ele).hide();}
let $grid=jQuery('.tstk-element-posts-wrapper',main_ele).masonry({itemSelector:'none',columnWidth:'.tstk-ele',gutter:0,percentPosition:true,stagger:30,visibleStyle:{transform:'translateY(0)',opacity:1},hiddenStyle:{transform:'translateY(100px)',opacity:0},});let msnry=$grid.data('masonry');$grid.imagesLoaded(function(){$grid.removeClass('are-images-unloaded');$grid.masonry('option',{itemSelector:'.tstk-ele'});let $items=$grid.find('.tstk-ele');$grid.masonry('appended',$items);});$grid.infiniteScroll({path:tstk_js_variables.ajaxurl+'?action=tstk_infinite_scroll&page_no={{#}}&nonce='+tstk_js_variables.ajaxnonce+url_attributes,append:'.tstk-ele',outlayer:msnry,status:'.tstk-infinite-loader',history:false,scrollThreshold:-200,});$grid.on('append.infiniteScroll',function(event,body,path,items,response){if(x>=totalpagination){jQuery('.tstk-infinite-loader',main_ele).addClass('tstk-infinite-loader-hide');jQuery('.tstk-infinite-scroll-last',main_ele).show();}
x++;});}});}}
var tstk_set_testimonial_right_column=function(){setTimeout(function(){jQuery('.tstk-element-testimonial-style-2').each(function(){var thisele=jQuery(this);if(jQuery(this).closest('.elementor-element.elementor-section-stretched.elementor-section-full_width')){var body_width=jQuery('body').outerWidth();var container_width=jQuery('.themestek-container',thisele).outerWidth();var padding_left=(body_width-container_width)/2;if(jQuery('body').hasClass('rtl')){jQuery('.themestek-testimonial-expand-right',thisele).css('padding-right',padding_left);}else{jQuery('.themestek-testimonial-expand-right',thisele).css('padding-left',padding_left);}}});},100);};var tstk_search_results=function(){if(jQuery('.tstk-search-results-main-wrapper').length>0&&jQuery('.tstk-search-result-tab-links').length>0){jQuery('.tstk-search-results-main-wrapper').skeletabs({keyboard:false});}
if(jQuery('.tstk-search-results-main-wrapper').length>0){jQuery('body').addClass('tstk-search-results-loaded');}}
var tstk_icon_box_hover_effect=function(){jQuery(".tstk-icon-box-hover-effect .elementor-element.elementor-widget-tstk_icon_heading").mouseover(function(){var main_row=jQuery(this).closest('.tstk-icon-box-hover-effect');jQuery('.elementor-element.elementor-widget-tstk_icon_heading',main_row).removeClass('tstk-ihbox-hover-active');jQuery(this).addClass('tstk-ihbox-hover-active');});}
var tstk_multi_icon_box_hover_effect=function(){jQuery(".tstk-multi-icon-box-hover-effect .tstk-miconheading-style-5:nth-child(2)").addClass('tstk-mihbox-hover-active');jQuery(".tstk-multi-icon-box-hover-effect .tstk-miconheading-style-5").mouseover(function(){var main_row=jQuery(this).closest('.tstk-multi-icon-box-hover-effect');jQuery('.tstk-miconheading-style-5',main_row).removeClass('tstk-mihbox-hover-active');jQuery(this).addClass('tstk-mihbox-hover-active');}).mouseout(function(){var main_row=jQuery(this).closest('.tstk-multi-icon-box-hover-effect');jQuery('.tstk-miconheading-style-5',main_row).removeClass('tstk-mihbox-hover-active');jQuery('.tstk-miconheading-style-5:nth-child(2)',main_row).addClass('tstk-mihbox-hover-active');});}
var tstk_validate=function(){jQuery("#commentform").submit(function(event){var error=false;jQuery('.tstk-form-error').hide();if(jQuery("#author").length>0&&!jQuery("#author").val()){jQuery('.comment-form-author .tstk-form-error').show();error=true;}
if(jQuery("#comment").length>0&&!jQuery("#comment").val()){jQuery('.comment-form-comment .tstk-form-error').show();error=true;}
if(jQuery("#email").length>0){if(!jQuery("#email").val()){jQuery('.comment-form-email .tstk-form-error.tstk-empty-email').show();error=true;}else{var valid_email=(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(jQuery("#email").val()));if(valid_email!=true){jQuery('.comment-form-email .tstk-form-error.tstk-invalid-email').show();error=true;}}}
if(error==true){event.preventDefault();return false;}else{return true;}});}
var tstk_ajax_pagination=function(){if(jQuery('.themestek-element.tstk-ajax-pagination-yes').length>0){jQuery('.themestek-element.tstk-ajax-pagination-yes').each(function(){var main_ele=jQuery(this);jQuery('.tstk-pagination a',main_ele).each(function(i,e){var link_href=jQuery(e).attr('href');var link_href_array=link_href.split("page");var page_number=link_href_array[link_href_array.length-1];page_number=page_number.replace("/","");page_number=page_number.replace("/","");page_number=page_number.replace("d=","");jQuery(e).attr('data-pagenum',page_number);})
jQuery('.tstk-pagination .page-numbers',main_ele).click(function(e){e.preventDefault();var thisEle=jQuery(this);if(thisEle.hasClass('current')){return;}
jQuery('.tstk-element-posts-wrapper',main_ele).addClass('tstk-ajax-loading');var div_pagination=jQuery(this).closest('.tstk-pagination');jQuery('a, .page-numbers',div_pagination).removeClass('current');jQuery(this).addClass('current');var pagination=1;if(jQuery(this).data('pagenum')!=''){pagination=jQuery(this).data('pagenum')}
var cpt=main_ele.data('cpt');var style=main_ele.data('style');var show=main_ele.data('show');var columns=main_ele.data('columns');var from_category=main_ele.data('sortby');var orderby='';var order='';var infinitre_scroll_data=jQuery('.tstk-infinite-scroll-data',main_ele).html();if(infinitre_scroll_data!=''){var url_attributes='';jQuery.each(jQuery.parseJSON(infinitre_scroll_data),function(key,value){if(key=='cpt'){cpt=value;}else if(key=='style'){style=value;}else if(key=='show'){show=value;}else if(key=='columns'){columns=value;}else if(key=='orderby'){orderby=value;}else if(key=='order'){order=value;}else if(key=='from_category'){from_category=value;}});}
jQuery.ajax({type:"post",url:tstk_js_variables.ajaxurl,data:{action:"tstk_ajax_pagination",cpt:cpt,style:style,show:show,columns:columns,from_category:from_category,orderby:orderby,order:order,pagination:pagination,nonce:tstk_js_variables.ajaxnonce_ajax_pagination},success:function(response){jQuery('.tstk-element-posts-wrapper',main_ele).removeClass('tstk-ajax-loading');jQuery('.tstk-element-posts-wrapper',main_ele).html(response);}});});});}}
jQuery(window).resize(function(){tstk_img_size_correction();});jQuery(document).ready(function(){tstk_validate();tstk_set_testimonial_right_column();tstk_search_results();tstk_toggleSidebar();tstk_tabs_element();tstk_sorting();tstk_ajax_sorting();tstk_back_to_top();tstk_sticky_header();tstk_navbar();tstk_lightbox();tstk_video_popup();tstk_testimonial();tstk_search_btn();tstk_center_logo_header_class();tstk_selectwrap();tstk_menu_count();setTimeout(function(){tstk_carousel();},200);tstk_img_size_correction();tstk_number_rotate();tstk_sticky_header_class();tstk_icon_box_hover_effect();tstk_multi_icon_box_hover_effect();scroll_heading_animation();tstk_ajax_pagination();});jQuery(window).load(function(){setTimeout(function(){tstk_anchor_auto_scroll_link();},500);tstk_one_page_on_scroll();tstk_anchor_link();tstk_preloader();tstk_sorting();tstk_gallery();tstk_circle_progressbar();tstk_infinite_scroll();setTimeout(function(){tstk_wc_cart_page_qty_update();},500);});jQuery(window).resize(function(){tstk_set_testimonial_right_column();});jQuery(window).on('scroll',function(){tstk_one_page_on_scroll();});